project:
  type: website
  output-dir: docs

website:
  favicon: StatLab_oficial.png
  page-navigation: true
  title: "StatLab"

  page-footer:
    background: dark
    left: "&copy; StatLab"
    center: "Departamento de Estatística e Matemática Aplicada | Universidade Federal do Ceará | Campus do Pici | Centro de Ciências | Bloco 910 | CEP: 60440-900 | Fortaleza-CE | +55 85 3366-9836 | statlab@ufc.br"
    right: "Desenvolvido com ❤️ e [Quarto](https://quarto.org/)."

  navbar:
    logo: StatLab_oficial.png
    logo-alt: "StatLab"
    left:
      - href: index.qmd
        text: Início

      - href: sobre/
        text: Sobre

      - href: pessoas/
        text: Pessoas

      - href: projects/
        text: Projetos e Ações

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lang: pt
    page-layout: full