project:
  type: website
  output-dir: docs
  

website:
  favicon: StatLab_oficial.png
  page-navigation: true
  title: "StatLab"
  
  

  page-footer:
    background: dark
    left: "&copy; Copyright 2024, StatLab"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    center: "Departamento de Estatística e Matemática Aplicada | Universidade Federal do Ceará | Campus do Pici | Centro de Ciências | Bloco 910 | CEP: 60440-900 | Fortaleza-CE | +55 85 3366-9836 | statlab@ufc.br "
  
  navbar:
    logo: StatLab_oficial.png
    logo-alt: "StatLab"
    left:
      - href: index.qmd
        text: Início

      - href: equipe.qmd
        text: Quem Somos
        
      - href: pessoas/pessoas.qmd
        text: Equipe
      
      - href: projects/index.qmd
        text: Projetos

     # - href: about.qmd
     #   text: Sobre
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lang: pt
    page-layout: full



