---
title: ""
about:
  template: solana
  image-shape: round
callout-icon: false
---

::: callout-tip
## Missão

<p id="para2">

O **Laboratório de Inovação em Estatística e Ciência de Dados (StatLab)** do Departamento de Estatística e Matemática Aplicada (DEMA) da Universidade Federal do Ceará (UFC) propõe unir práticas de ensino, pesquisa e extensão para desenvolver soluções inovadoras com base na Estatística e Ciência de Dados, atuando principalmente em ações de extensão na pesquisa, desenvolvimento de produtos e inovação, com objetivo de atender demandas específicas do setor público e privado. Este laboratório visa estabelecer um Hub de excelência que promova a extensão por meio do ensino e pesquisa aplicada, assim como a colaboração interinstitucional e a transferência de conhecimento para a comunidade através de suas ações.

</p>
:::

::: callout-tip
## Objetivos

**Geral:**

<p id="para2">

Consolidar o StatLab como um laboratório de referência em Estatística e Ciência de Dados que promova a integração eficaz de pesquisa, ensino e extensão, e que utilize o conhecimento científico para gerar impacto tangível na comunidade e no mercado.

</p>

**Específicos:**

-   <p id="para2">

    Realizar consultorias para organizações e entidades do setor público e privado.

    </p>

-   <p id="para2">

    Auxiliar na promoção da educação continuada em Estatística e Ciência de Dados através de atividades presenciais e via plataformas de aprendizado online, maximizando o alcance e a inclusão.

    </p>

-   <p id="para2">

    Desenvolver projetos de extensão que apliquem técnicas de Estatística e Ciência de Dados na solução de problemas reais da sociedade. Fomentar a colaboração entre a universidade e diversos setores da economia para promover a inovação.

    </p>

-   <p id="para2">

    Produção de relatório e artigos científicos com metodologias úteis para a sociedade.

    </p>

-   <p id="para2">

    Realizar ações de divulgação da área de Estatística e Ciência de Dados.

    </p>
:::
